name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - macos-14

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Latest Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        shell: bash
        run: |
          cargo build --all --release

          binary_extension=""

          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            binary_extension=".exe"
            binary_path="gitpull-windows-latest${binary_extension}"
          fi
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            if [[ "${MATRIX_OS}" == "macos-14" ]]; then
              binary_path="gitpull-macos-m1-latest"
            else
              binary_path="gitpull-macos-intel-latest"
            fi
          fi
          mv "target/release/gitpull${binary_extension}" "${binary_path}"
          echo "${binary_path}" > binary_path.txt

      - name: Install UPX
        run: sudo apt-get install -y upx

      - name: Compress Binary with UPX
        run: |
          binary_path=$(cat binary_path.txt)
          upx --best "${binary_path}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-binary
          path: ${{ env.binary_path }}
