name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: gitpull-macos-aarch64
            asset_name: gitpull
          - os: macos-11
            artifact_name: gitpull-macos-x86_64
            asset_name: gitpull
          - os: windows-latest
            artifact_name: gitpull-windows-amd64.exe
            asset_name: gitpull.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --locked

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/${{ matrix.asset_name }}

  create-universal-binary:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Download aarch64 artifact
        uses: actions/download-artifact@v3
        with:
          name: gitpull-macos-aarch64

      - name: Download x86_64 artifact
        uses: actions/download-artifact@v3
        with:
          name: gitpull-macos-x86_64

      - name: Combine binaries
        run: |
          lipo -create -output gitpull gitpull-macos-aarch64/gitpull gitpull-macos-x86_64/gitpull

      - name: Upload universal binary
        uses: actions/upload-artifact@v3
        with:
          name: gitpull-macos-universal
          path: gitpull
