name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: gitpull-macos-universal
            asset_name: gitpull
          - os: windows-latest
            artifact_name: gitpull-windows-amd64.exe
            asset_name: gitpull.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin  # 为 macOS 添加 ARM 和 Intel 目标

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            cargo build --release --locked --target=aarch64-apple-darwin
            cargo build --release --locked --target=x86_64-apple-darwin
            lipo -create -output target/release/${{ matrix.asset_name }} target/aarch64-apple-darwin/release/${{ matrix.asset_name }} target/x86_64-apple-darwin/release/${{ matrix.asset_name }}
          else
            cargo build --release --locked
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/${{ matrix.asset_name }}
