name: Build Rust Project for macOS and Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact-name: gitpull-macos
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact-name: gitpull-windows

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        profile: minimal
        override: true

    - name: Cache Cargo dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }} --verbose

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact-name }}
        path: target/${{ matrix.target }}/release/gitpull
